# Generated by Django 5.0.2 on 2024-02-27 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='job_title',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
